### ISSUE TITLE
version_dir and scripts_dir do not exist in attributes/default.rb and README.md

### ISSUE THREAD

**Issue by CpuID** [vkhatri/chef-consul-ng#16]
If using the individual `consul-ng::install` and `consul-ng::config` recipes, without specifying the `default['consul']['version_dir']` and `default['consul']['scripts_dir']` values in an attributes file, you end up with an error like this:

```
       ArgumentError
       -------------
       You must supply a name when declaring a directory resource
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/consul-ng/recipes/install.rb:34:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/consul-ng/recipes/install.rb:33:in `each'
         /tmp/kitchen/cache/cookbooks/consul-ng/recipes/install.rb:33:in `from_file'
       
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/consul-ng/recipes/install.rb:
       
        27:   node['consul']['version_dir'],
        28:   node['consul']['conf_dir'],
        29:   node['consul']['scripts_dir'],
       
        31:   node['consul']['config']['data_dir'],
        32:   node['consul']['log_dir']
       
        34>>   directory dir do
        35:      owner node['consul']['user']
        36:      group node['consul']['group']
        37:      mode node['consul']['mode']
        38:      recursive true
```

This looks to be due to variables that do not exist, being used as inputs to the `.each`.

Specifying them in the `attributes/default.rb`, in addition to the `README.md` would be ideal to avoid such an error on a fresh setup :)

**Comment by vkhatri** [comment]
@CpuID Keeping the attributes in default recipe works for config, install and other recipes to maintain attributes precedence.

How about adding a switch to disable install and config recipe? this way one can choose install or config recipe.

```ruby
default['consul']['configure'] = true
default['consul']['install'] = true

**Comment by vkhatri** [comment]
Published new version. Please reopen if required.
